module.exports = {
  googleIcon: require('@assets/images/auth/google.png'),
  fbIcon: require('@assets/images/auth/fb.png'),
  appleIcon: require('@assets/images/auth/apple.png'),
  editIcon: require('@assets/images/auth/edit.png'),

  onBoarding1: require('@assets/images/onBoarding/onBoarding1.jpg'),
  onBoarding2: require('@assets/images/onBoarding/onBoarding2.jpg'),
  onBoarding3: require('@assets/images/onBoarding/onBoarding3.jpg'),
  logo: require('@assets/images/logo/mint-logo-black.png'),
  darkLogo: require('@assets/images/logo/mint-logo-white.png'),
  logo2: require('@assets/images/logo/mint-logo-black.png'),
  logo3: require('@assets/images/logo/mint-logo-black.png'),
  divider: require('@assets/images/divider.png'),
  darkDivider: require('@assets/images/darkDivider.png'),
  user: require('@assets/images/image/user.png'),
  womenImage: require('@assets/images/home/home_category/women.png'),
  menImage: require('@assets/images/home/home_category/men.png'),
  kidsImage: require('@assets/images/home/home_category/kid.png'),
  beautyImage: require('@assets/images/home/home_category/beauty.png'),
  footwearImage: require('@assets/images/home/home_category/footwear.png'),
  jewelleryImage: require('@assets/images/home/home_category/jewellery.png'),

  inverterImage: require('@assets/images/home/home_category/inverter.png'),
  batteryImage: require('@assets/images/home/home_category/batteries.png'),
  waterPumpImage: require('@assets/images/home/home_category/waterpump.png'),
  generatorImage: require('@assets/images/home/home_category/generators.png'),
  powerStationImage: require('@assets/images/home/home_category/powerstation.png'),
  solarImage: require('@assets/images/home/home_category/solar.png'),
  accessoriesImage: require('@assets/images/home/home_category/accessories.png'),

  dealOfTheDay1: require('@assets/images/home/home_deals/dealOfTheDay1.png'),
  dealOfTheDay2: require('@assets/images/home/home_deals/dealOfTheDay2.jpeg'),
  dealOfTheDay3: require('@assets/images/home/home_deals/dealOfTheDay3.png'),

  findStyle1: require('@assets/images/home/find_style/findStyle1.png'),
  findStyle2: require('@assets/images/home/find_style/findStyle2.png'),
  findStyle3: require('@assets/images/home/find_style/findStyle3.png'),
  findStyle4: require('@assets/images/home/find_style/findStyle4.png'),
  findStyle5: require('@assets/images/home/find_style/findStyle5.png'),

  banner1Image: require('@assets/images/home/home_banner/banner1.jpg'),
  banner2Image: require('@assets/images/home/home_banner/banner2.jpg'),
  banner3Image: require('@assets/images/home/home_banner/banner3.jpg'),
  banner4Image: require('@assets/images/home/home_banner/banner4.jpg'),

  deliverBanner: require('@assets/images/home/home_banner/deliverBanner.jpg'),

  addToCart: require('@assets/images/add-to-cart-black.png'),
  addedToCart: require('@assets/images/added-to-cart-black.png'),
  addToCartWhite: require('@assets/images/add-to-cart-white.png'),
  addedToCartWhite: require('@assets/images/added-to-cart-white.png'),

  homeDivider: require('@assets/images/home/divider.png'),
  denimWear: require('@assets/images/home/denimWear.png'),

  callIcon: require('@assets/images/headset.png'),
  emailIcon: require('@assets/images/email-outline.png'),
  whatsappIcon: require('@assets/images/whatsapp.png'),
  websiteIcon: require('@assets/images/internet-outline.png'),
  facebookIcon: require('@assets/images/facebook2.png'),
  instagramIcon: require('@assets/images/instagram.png'),

  elmCollection: require('@assets/images/image/elm.png'),
  comoCollection: require('@assets/images/image/como.jpg'),
  emersonCollection: require('@assets/images/image/emerson.jpg'),
  madelineCollection: require('@assets/images/image/madeline.jpg'),
  belleCollection: require('@assets/images/image/belle.jpg'),
  amalfiCollection: require('@assets/images/image/amalfi.jpg'),
  hamiltonCollection: require('@assets/images/image/hamilton.jpg'),
  arrowCollection: require('@assets/images/image/arrow.jpg'),
  sophieCollection: require('@assets/images/image/sophie.jpg'),
  palletCollection: require('@assets/images/image/pallet.jpg'),
  scandinavianCollection: require('@assets/images/image/scandi.jpg'),
  bordeauxCollection: require('@assets/images/image/bordeaux.jpg'),
  zeldaCollection: require('@assets/images/image/zelda.jpg'),
  koshaCollection: require('@assets/images/image/kosha.jpg'),
  industrialCollection: require('@assets/images/image/industrial.jpg'),
  hairpinCollection: require('@assets/images/image/hairpin.jpg'),
  corporateCollection: require('@assets/images/image/corporate.jpg'),
  arabicCollection: require('@assets/images/image/arabic.jpg'),
  outdoorSeatingCollection: require('@assets/images/image/polka.jpg'),



  privacyIcon: require('@assets/images/privacy.png'),

  biggestDeal1: require('@assets/images/brands/brand1.jpg'),
  biggestDeal2: require('@assets/images/brands/brand2.jpg'),
  biggestDeal3: require('@assets/images/brands/brand3.jpg'),
  biggestDeal4: require('@assets/images/brands/brand4.jpg'),
  biggestDeal5: require('@assets/images/brands/brand5.jpg'),
  biggestDeal6: require('@assets/images/brands/brand6.jpg'),
  biggestDeal7: require('@assets/images/brands/brand7.jpg'),
  biggestDeal8: require('@assets/images/brands/brand8.jpg'),
  biggestDeal9: require('@assets/images/brands/brand9.jpg'),
  biggestDeal10: require('@assets/images/brands/brand10.jpg'),
  biggestDeal11: require('@assets/images/brands/brand11.jpg'),
  biggestDeal12: require('@assets/images/brands/brand12.jpg'),
  biggestDeal13: require('@assets/images/brands/brand13.jpg'),
  biggestDeal14: require('@assets/images/brands/brand14.jpg'),
  biggestDeal15: require('@assets/images/brands/brand15.jpg'),
  biggestDeal16: require('@assets/images/brands/brand16.jpg'),
  biggestDeal17: require('@assets/images/brands/brand17.jpg'),
  biggestDeal18: require('@assets/images/brands/brand18.jpg'),
  biggestDeal19: require('@assets/images/brands/brand19.jpg'),
  biggestDeal20: require('@assets/images/brands/brand20.jpg'),
  biggestDeal21: require('@assets/images/brands/brand21.jpg'),

  category1: require('@assets/images/category/category1.png'),
  category2: require('@assets/images/category/category2.png'),
  category3: require('@assets/images/category/category3.png'),
  category4: require('@assets/images/category/category4.png'),
  category5: require('@assets/images/category/category5.png'),
  category6: require('@assets/images/category/category6.png'),
  category7: require('@assets/images/category/category7.png'),

  category21: require('@assets/images/category/category21.png'),
  category22: require('@assets/images/category/category22.png'),
  category23: require('@assets/images/category/category23.png'),
  category24: require('@assets/images/category/category24.png'),
  category25: require('@assets/images/category/category25.png'),
  category26: require('@assets/images/category/category26.png'),
  category27: require('@assets/images/category/category27.png'),

  denim: require('@assets/images/category/denim.png'),
  flowerprint: require('@assets/images/category/flowerprint.png'),
  skirts: require('@assets/images/category/skirts.png'),
  settings: require('@assets/images/setting.jpeg'),

  kidsCorner1: require('@assets/images/home/kids_corner/kidsCorner1.jpeg'),
  kidsCorner2: require('@assets/images/home/kids_corner/kidsCorner2.jpeg'),
  kidsCorner3: require('@assets/images/home/kids_corner/kidsCorner3.jpeg'),

  emptyStar: require('@assets/images/image/emptyStar.png'),
  filledStar: require('@assets/images/image/filledStar.png'),
  map: require('@assets/images/image/map.png'),
  darkMap: require('@assets/images/image/mapDark.png'),
  person: require('@assets/images/image/avtar.png'),
  person1: require('@assets/images/image/avtar1.png'),
  aboutUs: require('@assets/images/image/aboutUs.jpg'),
  aboutUs1: require('@assets/images/image/aboutus-1.jpg'),
  aboutUs2: require('@assets/images/image/aboutus-2.jpg'),
  helpCenter: require('@assets/images/image/helpCenter.png'),
  darkmapsection: require('@assets/images/product/darkmapsection.png'),

  sale: require('@assets/images/sale.gif'),

  truckDelivery: require('@assets/images/gif/truckDelivery.gif'),

  product1: require('@assets/images/product/product1.png'),
  product2: require('@assets/images/product/product2.png'),
  product3: require('@assets/images/product/product3.jpg'),
  product4: require('@assets/images/product/product4.png'),
  product5: require('@assets/images/product/product5.jpg'),
  product6: require('@assets/images/product/product6.jpg'),
  product7: require('@assets/images/product/product7.jpg'),
  product8: require('@assets/images/product/product8.jpg'),
  product9: require('@assets/images/product/product9.jpg'),
  product10: require('@assets/images/product/product10.jpg'),
  product11: require('@assets/images/product/product11.jpeg'),
  product12: require('@assets/images/product/product12.jpeg'),
  product13: require('@assets/images/product/product13.jpeg'),
  product14: require('@assets/images/product/product14.jpg'),
  product15: require('@assets/images/product/product15.jpg'),
  product16: require('@assets/images/product/product16.jpg'),
  product17: require('@assets/images/product/product17.png'),
  product18: require('@assets/images/product/product18.png'),
  product19: require('@assets/images/product/product19.png'),
  product20: require('@assets/images/product/product20.png'),
  product21: require('@assets/images/product/product21.png'),
  product22: require('@assets/images/product/product22.png'),
  mapImage: require('@assets/images/product/mapSection.png'),
  coupenCode: require('@assets/images/product/coupenCode.png'),

  brand1: require('@assets/images/brands/brand1.png'),
  brand2: require('@assets/images/brands/brand2.png'),
  brand3: require('@assets/images/brands/brand3.png'),
  brand4: require('@assets/images/brands/brand4.png'),
  brand5: require('@assets/images/brands/brand5.png'),
  brand6: require('@assets/images/brands/brand6.png'),

  // brand1: require('@assets/images/brands/kubota.png'),
  // brand2: require('@assets/images/brands/bluetti.png'),
  // brand3: require('@assets/images/brands/dewalt.jpg'),
  // brand4: require('@assets/images/brands/honda.jpg'),
  // brand5: require('@assets/images/brands/perkins.jpg'),
  // brand6: require('@assets/images/brands/saer.jpg'),
  // brand7: require('@assets/images/brands/yanmar.png'),


  emptyCart: require('@assets/images/emptyCart.png'),
  checkCircle: require('@assets/images/gif/checkCircle.gif'),
  noData: require('@assets/images/noData.png'),

  cash: require('@assets/images/paymentIcon/cash.png'),
  credit: require('@assets/images/paymentIcon/credit.png'),
  netBanking: require('@assets/images/paymentIcon/netBanking.png'),
  wallets: require('@assets/images/paymentIcon/wallets.png'),
  cashDark: require('@assets/images/paymentIcon/cashDark.png'),
  creditDark: require('@assets/images/paymentIcon/creditDark.png'),
  netBankingDark: require('@assets/images/paymentIcon/netBankingDark.png'),
  walletsDark: require('@assets/images/paymentIcon/walletsDark.png'),

  blueCard: require('@assets/images/paymentCard/blueCard.png'),
  logo: require('@assets/images/paymentCard/logo.png'),
  purpleCard: require('@assets/images/paymentCard/purpleCard.png'),
  yellowCard: require('@assets/images/paymentCard/yellowCard.png'),
  chipImg: require('@assets/images/paymentCard/chipImg.png'),
  paytmLogo: require('@assets/images/paymentCard/paytmlogo.png'),
  googleLogo: require('@assets/images/paymentCard/Google.png'),
  cashLogo: require('@assets/images/paymentCard/cashLogo.png'),
};
